Di 365 v1.1.0
eastgenomics/eggd_dias_cnvreports_workflow pull request #6
Opened 2023-08-01 13:28 UTC by kjwinfield

### eggd_dias_cnvreports_workflow 1.1.0

**Changes**

- eggd_dias_cnvreports_workflow version number updated
- stage IDs renamed; these names are more self-explanatory
- update app versions to newest current version. All apps were already up-to-date except eggd_generate_variant_workbook:
  - eggd_generate_variant_workbook: v2.2.0 > v2.5.0
- move some inputs from the workflow to the config (new config version egg5_dias_CEN_config 2.1.0). The inputs moved are as follows:
      -  stage-cnv_generate_bed_excluded.flank
      -  stage-cnv_generate_workbook.additional_sheet_names
      -  stage-cnv_generate_workbook.exclude_columns
      -  stage-cnv_generate_workbook.reorder_columns
      -  stage-cnv_generate_workbook.add_comment_column
      -  stage-cnv_generate_workbook.summary

**Testing**

Testing and development were done in this project: [https://platform.dnanexus.com/projects/GXx4bg04XZB63XqK9xpPKvy9/monitor](https://platform.dnanexus.com/projects/GXx4bg04XZB63XqK9xpPKvy9/monitor)
The DNAnexus workflow ID of the eggd_dias_cnvreports_workflow 1.1.0 workflow tested is workflow-GXzvJq84XZB1fJk9fBfG88XJ ([link](https://platform.dnanexus.com/panx/projects/GXx4bg04XZB63XqK9xpPKvy9/data/?scope=project&id.values=workflow-GXzvJq84XZB1fJk9fBfG88XJ))
![Screenshot from 2023-07-25 14-58-48](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/assets/71272357/98c8a1bb-8afb-4450-b1de-24608c7c368f)

**Works for both Epic and Gemini style manifestos**
Example using Epic manifesto: [analysis-GXzvPQ84XZB46JFgJBpYJF4v](https://platform.dnanexus.com/projects/GXx4bg04XZB63XqK9xpPKvy9/monitor/analysis/GXzvPQ84XZB46JFgJBpYJF4v)
Example using Gemini manifesto: [analysis-GXvbbjQ4YXKZ89jg9jPbj93P](https://platform.dnanexus.com/projects/GXv0Xz84YXKzQYxkK35144Jf/monitor/analysis/GXvbbjQ4YXKZ89jg9jPbj93P)
 
**All stages renamed and app versions updated**
`dx describe analysis-GXzvPPj4XZBPfxx6j0yZv53F` and `dx describe analysis-GXzvx104XZBJPXG1bZ438x12` were run to check all the stages in the process had been renamed correctly and use the correct app versions for both Epic and Gemini manifesto styles.
This screenshot shows that the app versions and stage names match the expected updated versions, using an Epic-style manifesto:
![Screenshot from 2023-07-25 15-07-23](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/assets/71272357/9aeab810-4338-4a7c-8947-a60960403328)
This screenshot shows that the app versions and stage names match the expected updated versions, using a Gemini-style manifesto:
![Screenshot from 2023-07-25 15-04-07](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/assets/71272357/0cbbfbc7-c6a3-48bd-8659-1067ad8c4bd0)

2023-08-01 14:09 UTC, kjwinfield commented
**Test that it finds known variants**
The Gemini variant samples tested with new version 1.1.0 had known CNVs present. 
Jobs were checked to see that a CNV had been reported for them e.g. for sample GM2301875, run on this job ([link](https://platform.dnanexus.com/projects/GXv0Xz84YXKzQYxkK35144Jf/monitor/analysis/GXvbbjQ4YXKZ89jg9jPbj93P)) a CNV was reported in the workbook generated as seen in the screenshots below
![Screenshot from 2023-08-01 15-06-15](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/assets/71272357/2f980d40-c0be-482e-b9f9-3e8b1b44df5a)
![Screenshot from 2023-08-01 15-08-11](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/assets/71272357/24000c89-4823-48af-b6e0-1799d2ac5170)

2023-08-01 15:38 UTC, chrispyatt approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)



<!-- Sent from Reviewable.io -->

2023-08-01 16:12 UTC, chrispyatt requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6)* status: all files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`dxworkflow.json` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6#-NalrhBOC9PZouHbI9ac:-NalrhBOC9PZouHbI9ad:b-43kxq5) ([raw file](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/blob/41b1732ad1de7c6243e554e7dc2cd9c078dea7c5/dxworkflow.json#L30)):*
> ```JSON
>       "id": "stage-cnv_vep",
>       "executable": "app-eggd_vep/1.1.0",
>       "normalise": false,
> ```

should normalise be within the input bit?


<!-- Sent from Reviewable.io -->

2023-08-01 16:15 UTC, mattgarner reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6)* status: all files reviewed, 1 unresolved discussion (waiting on @kjwinfield)



<!-- Sent from Reviewable.io -->

2023-08-02 09:34 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @chrispyatt)

___
*[`dxworkflow.json` line 30 at r2](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6#-NalrhBOC9PZouHbI9ac:-NapaI2O7f647GHWhQPo:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_dias_cnvreports_workflow/blob/41b1732ad1de7c6243e554e7dc2cd9c078dea7c5/dxworkflow.json#L30)):*
<details><summary><i>Previously, chrispyatt (Chris Pyatt) wrote…</i></summary><blockquote>

should normalise be within the input bit?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-02 09:36 UTC, chrispyatt approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_cnvreports_workflow/6)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @kjwinfield)



<!-- Sent from Reviewable.io -->

2023-08-02 09:37 UTC, merged